"""initial schema

Revision ID: 26ce5ddc18e1
Revises: 
Create Date: 2026-07-17 19:45:09.082754

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26ce5ddc18e1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_code'), 'features', ['code'], unique=True)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', name='organization_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('products',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('active', 'retired', name='product_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_table('signing_keys',
    sa.Column('key_id', sa.String(length=200), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.Enum('active', 'retired', name='signing_key_status'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('normalized_email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'disabled', name='user_status'), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vendor_role', sa.Enum('vendor_super_admin', 'vendor_support', name='vendor_role'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_normalized_email'), 'users', ['normalized_email'], unique=True)
    op.create_table('activation_requests',
    sa.Column('user_code_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'denied', 'expired', 'consumed', name='activation_request_status'), nullable=False),
    sa.Column('requested_product_code', sa.String(length=100), nullable=False),
    sa.Column('requested_edition_code', sa.String(length=100), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_organization_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['approved_organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activation_requests_expires_at'), 'activation_requests', ['expires_at'], unique=False)
    op.create_index(op.f('ix_activation_requests_user_code_hash'), 'activation_requests', ['user_code_hash'], unique=True)
    op.create_table('audit_events',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.String(length=200), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('source_ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_table('editions',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('active', 'retired', name='edition_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'code', name='uq_edition_product_code')
    )
    op.create_index(op.f('ix_editions_product_id'), 'editions', ['product_id'], unique=False)
    op.create_table('organization_memberships',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('organization_admin', 'organization_member', name='membership_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'removed', name='membership_status'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_org_memberships_active_unique', 'organization_memberships', ['organization_id', 'user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_index(op.f('ix_organization_memberships_organization_id'), 'organization_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_user_id'), 'organization_memberships', ['user_id'], unique=False)
    op.create_table('edition_features',
    sa.Column('edition_id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.PrimaryKeyConstraint('edition_id', 'feature_id')
    )
    op.create_table('organization_licenses',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('edition_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'suspended', 'expired', 'revoked', name='organization_license_status'), nullable=False),
    sa.Column('seat_limit', sa.Integer(), nullable=False),
    sa.Column('device_limit_per_user', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('offline_validity_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('device_limit_per_user >= 1', name='ck_org_license_device_limit_positive'),
    sa.CheckConstraint('seat_limit >= 0', name='ck_org_license_seat_limit_nonneg'),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_licenses_edition_id'), 'organization_licenses', ['edition_id'], unique=False)
    op.create_index(op.f('ix_organization_licenses_organization_id'), 'organization_licenses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_licenses_product_id'), 'organization_licenses', ['product_id'], unique=False)
    op.create_table('device_activations',
    sa.Column('organization_license_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_public_key', sa.LargeBinary(), nullable=False),
    sa.Column('device_public_key_hash', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'revoked', 'replaced', name='device_activation_status'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_renewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_user_id', sa.UUID(), nullable=True),
    sa.Column('revocation_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_license_id'], ['organization_licenses.id'], ),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_activations_device_public_key_hash'), 'device_activations', ['device_public_key_hash'], unique=True)
    op.create_index(op.f('ix_device_activations_organization_license_id'), 'device_activations', ['organization_license_id'], unique=False)
    op.create_index(op.f('ix_device_activations_user_id'), 'device_activations', ['user_id'], unique=False)
    op.create_table('license_seat_assignments',
    sa.Column('organization_license_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'removed', name='seat_assignment_status'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_license_id'], ['organization_licenses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_seat_assignments_organization_license_id'), 'license_seat_assignments', ['organization_license_id'], unique=False)
    op.create_index(op.f('ix_license_seat_assignments_user_id'), 'license_seat_assignments', ['user_id'], unique=False)
    op.create_index('ix_seat_assignments_active_unique', 'license_seat_assignments', ['organization_license_id', 'user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('issued_license_certificates',
    sa.Column('license_id', sa.UUID(), nullable=False),
    sa.Column('device_activation_id', sa.UUID(), nullable=False),
    sa.Column('license_version', sa.Integer(), nullable=False),
    sa.Column('signing_key_id', sa.String(length=200), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('active', 'revoked', 'superseded', name='issued_certificate_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['device_activation_id'], ['device_activations.id'], ),
    sa.ForeignKeyConstraint(['signing_key_id'], ['signing_keys.key_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issued_license_certificates_device_activation_id'), 'issued_license_certificates', ['device_activation_id'], unique=False)
    op.create_index(op.f('ix_issued_license_certificates_license_id'), 'issued_license_certificates', ['license_id'], unique=False)
    op.create_table('refresh_challenges',
    sa.Column('device_activation_id', sa.UUID(), nullable=False),
    sa.Column('nonce_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['device_activation_id'], ['device_activations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_challenges_device_activation_id'), 'refresh_challenges', ['device_activation_id'], unique=False)
    op.create_index(op.f('ix_refresh_challenges_expires_at'), 'refresh_challenges', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_challenges_nonce_hash'), 'refresh_challenges', ['nonce_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_challenges_nonce_hash'), table_name='refresh_challenges')
    op.drop_index(op.f('ix_refresh_challenges_expires_at'), table_name='refresh_challenges')
    op.drop_index(op.f('ix_refresh_challenges_device_activation_id'), table_name='refresh_challenges')
    op.drop_table('refresh_challenges')
    op.drop_index(op.f('ix_issued_license_certificates_license_id'), table_name='issued_license_certificates')
    op.drop_index(op.f('ix_issued_license_certificates_device_activation_id'), table_name='issued_license_certificates')
    op.drop_table('issued_license_certificates')
    op.drop_index('ix_seat_assignments_active_unique', table_name='license_seat_assignments', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_license_seat_assignments_user_id'), table_name='license_seat_assignments')
    op.drop_index(op.f('ix_license_seat_assignments_organization_license_id'), table_name='license_seat_assignments')
    op.drop_table('license_seat_assignments')
    op.drop_index(op.f('ix_device_activations_user_id'), table_name='device_activations')
    op.drop_index(op.f('ix_device_activations_organization_license_id'), table_name='device_activations')
    op.drop_index(op.f('ix_device_activations_device_public_key_hash'), table_name='device_activations')
    op.drop_table('device_activations')
    op.drop_index(op.f('ix_organization_licenses_product_id'), table_name='organization_licenses')
    op.drop_index(op.f('ix_organization_licenses_organization_id'), table_name='organization_licenses')
    op.drop_index(op.f('ix_organization_licenses_edition_id'), table_name='organization_licenses')
    op.drop_table('organization_licenses')
    op.drop_table('edition_features')
    op.drop_index(op.f('ix_organization_memberships_user_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_organization_id'), table_name='organization_memberships')
    op.drop_index('ix_org_memberships_active_unique', table_name='organization_memberships', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('organization_memberships')
    op.drop_index(op.f('ix_editions_product_id'), table_name='editions')
    op.drop_table('editions')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_activation_requests_user_code_hash'), table_name='activation_requests')
    op.drop_index(op.f('ix_activation_requests_expires_at'), table_name='activation_requests')
    op.drop_table('activation_requests')
    op.drop_index(op.f('ix_users_normalized_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('signing_keys')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_features_code'), table_name='features')
    op.drop_table('features')
    # ### end Alembic commands ###
